### ISSUE TITLE
Master Menu and Daily Menu seperation

### ISSUE THREAD

**Issue by abhishekc-sharma** [ananya0996/foodiction#2]
The menu page that has currently been implemented is directly linked to the menu that the customer will see. We are planning to allow the canteen to modify the menu on a day to day basis. However, in the current minimal implementation there is no way for an item to be removed temporarily for some duration of days and then added back. Once removed, it is removed permanently.

To handle this we require two interfaces for the canteen

## Master Menu 
- [x] View Items in the Master Menu
- [x] Add Items to the Master Menu. This includes name and price of the Item. Need to also indicate the required amounts of Ingredients for a particular number of Units of the Item.
- [x] Remove Items from Master Menu

## Daily Menu 
- [x] View Items in Daily Menu
- [x] Add Items from those in Master Menu to Daily Menu. Need to also set the intended number of units of a particular item that are to be allocated for the day so that ingredients from the inventory can be set aside. 
- [x] Remove Items from Daily Menu. Should not affect the Master Menu

## Current Implementation
The current implementation for menu resembles that of the Master Menu. There is a single Collection in the database called `items`. To handle the use cases mentioned here, we may have to create another collection to handle the Daily Menu part of it.

**Comment by ananya0996** [comment]
Is the canteen staff required to select items one at a time from the master menu and add to the daily menu? Or are we going to store a bunch of ready-to-use daily menus in a collection  (the items in which refer to those in the main menu, of course) which can be selected at the beginning of the day with a single click?
