### ISSUE TITLE
Order Servicing

### ISSUE THREAD

**Issue by abhishekc-sharma** [ananya0996/foodiction#3]
Currently the feature to mark an order as serviced is not functional

- [x] Mark order as serviced on pending orders page
- [x] Remove order from Orders collection on DB
- [x] Remove it from the pending orders page

**Comment by ananya0996** [comment]
> Remove order from Orders collection on DB

Can't we have an extra parameter to denote the status (pending / served) in the collection instead of removing orders from the DB itself? We'll need order data for analytics.

**Comment by ananya0996** [comment]
Are we letting the user cancel his/her order? If required, we can provide a 5-minute (or any other suitable duration) window allowing the user to cancel an order.

**Comment by akashpb** [comment]
What Ananya said is right. Let's incorporate whatever she said.

**Comment by abhishekc-sharma** [comment]
Yeah, we can definitely implement these. At the same time, there are other
features that are more critical to the entire application that still need
to be implemented so these are a lower priority for now. That said, feel
free to assign it to yourself and implement it 😁
